91-AddCounterCartNavBar :: Added cart counter and showing in navbar
TeamCharles/initial-site pull request #125
Opened 2016-10-27 21:22 UTC by daynewright

## Status
**READY/IN DEVELOPMENT**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

Calculates the line item count of products and adds them to base model.  Displays it on by the cart icon in the navbar.

## Resolves Issue Number
#91 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 91-AddCounterCartNavBar
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1.  dotnet run
2.  select user
IF (order exists)
       3. cart icon should show a counter of items on the order
ELSE
       3. select product
       4. add to cart
       5. counter should show 1

## Impacted Files in Application
List general components of the application that this PR will affect:

* Controllers/CartController.cs
* ViewModels/Base.cs
* Views/Shared/_NavbarView.cshtml

2016-10-27 23:10 UTC, MattKraatz requested changes
LGTM after a quick style guide change

2016-10-27 23:10 UTC, MattKraatz commented on ViewModels/Base.cs
> +        var CartProducts = (
explicit declaration please, I think:
`List<Product> CartProducts = (`

2016-10-28 01:25 UTC, Anulfo reviewed
LGTM

2016-10-28 02:26 UTC, daynewright commented on ViewModels/Base.cs
> +        var CartProducts = (
@MattKraatz  I changed it to add the `CartProducts` in the constructor on the base.  I removed the LINQ query from the cart controller and just use this instance of it in that cart view.  Seemed to be more DRY.  Also added comments.  All that to say you might want to review the changes and test again.

2016-10-28 02:44 UTC, MattKraatz approved these changes

2016-10-28 02:46 UTC, MattKraatz commented
LGTM

2016-10-28 13:09 UTC, garrett-vangilder commented
LGTM

2016-10-28 14:34 UTC, merged