105 product detail vew
TeamCharles/initial-site pull request #137
Opened 2016-10-29 16:07 UTC by garrett-vangilder

## Status
**READY/IN DEVELOPMENT**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

This PR adds some small styling to the Product Detail View

## Resolves Issue Number

#105 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 105-product-detail-view
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Go to a product view and look at that page. 
2. Sign in and go to a different product view for a product that you are not selling, then view a product you are selling.
3. Collect.

## Impacted Files in Application
List general components of the application that this PR will affect:

* Views/Products/Detail.cshtml

2016-10-30 22:33 UTC, MattKraatz approved these changes
LGTM

2016-10-31 13:55 UTC, matthamil commented
LGTM :tada:

2016-10-31 14:58 UTC, daynewright commented on Views/Products/Detail.cshtml
> +            <a asp-controller="Products" asp-action="Delete" asp-route-id="@Model.CurrentProduct.ProductId"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
I think we should make the `Add To Cart` link into a button.  We can just add `class="btn btn-primary btn-xs"` to the `a` tag.

2016-10-31 15:01 UTC, daynewright requested changes
Can we change the `Add to Cart` to a button?

2016-10-31 15:01 UTC, daynewright commented on Views/Products/Detail.cshtml
> +            <a asp-controller="Products" asp-action="Delete" asp-route-id="@Model.CurrentProduct.ProductId"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
I think we should make the `Add To Cart` link into a button.  We can just add `class="btn btn-primary btn-xs"` to the `a` tag.

2016-10-31 15:03 UTC, Anulfo commented
LGTM

2016-10-31 15:14 UTC, garrett-vangilder commented on Views/Products/Detail.cshtml
> +            <a asp-controller="Products" asp-action="Delete" asp-route-id="@Model.CurrentProduct.ProductId"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
Certainly

2016-10-31 15:20 UTC, garrett-vangilder commented
@daynewright your button is here.

2016-10-31 15:21 UTC, daynewright approved these changes

2016-10-31 15:28 UTC, merged