39 create product view
TeamCharles/initial-site pull request #71
Opened 2016-10-24 20:58 UTC by Anulfo

## Status
READY

## Documentation

[x ] I have fully documented features in this PR. Please put an `X` in the box to confirm.

## Migrations
YES

## Description
On ProductsController... 2 "Create" methods were created. The first one retrieve data to the dropdown lists of ProductType and for the User. The second method is an overload of "Create" to Post new products to the database

## Related PRs

branch | PR
------ | ------
39-createProductView

## Resolves Issue Number
resolves #39

## Deploy Notes
git run

## Steps to Test or Reproduce
git pull --prune
git checkout 39-createProductView
Delete Migrations folder and Database: rm Migrations and Bagazon.db
dotnet ef migrations add <nameofthemigration>
dotnet ef database update
dotnet restore
dotnet run
```

1. 

## Impacted Areas in Application
View for the form to post a new object to database

2016-10-24 23:14 UTC, MattKraatz requested changes
It works!

2016-10-24 23:14 UTC, MattKraatz commented on Controllers/ProductsController.cs
> +        [HttpGet]
I don't think this qualifies as a `Get` since we are just loading a view. I think we can remove line 60.

2016-10-24 23:14 UTC, MattKraatz commented on Controllers/ProductsController.cs
> +            Console.WriteLine($"ModelState.IsValid={ModelState.IsValid}");
I don't think we should commit Console.WriteLine() lines to master

2016-10-24 23:14 UTC, MattKraatz commented on Models/ProductType.cs
> +    public ICollection<Product> Products;
I don't think we need this on the model.

2016-10-24 23:14 UTC, MattKraatz commented on Views/Products/Create.cshtml
> +            <label asp-for="ProductTypeId" class="col-md-2 control-label"></label>
Let's add a label to this like "Product Type" or something
`<label asp-for="ProductTypeId" class="col-md-2 control-label">Product Type</label>`

2016-10-24 23:14 UTC, MattKraatz commented on Views/Products/Create.cshtml
> +            <label asp-for="UserId" class="col-md-2 control-label"></label>
I'll add a separate issue about removing this when we can reference Active User.

2016-10-24 23:14 UTC, MattKraatz commented on Views/Products/Create.cshtml
> +                <input type="submit" value="Save" class="btn btn-default" />
This value should be "Add New Product" per the user story.
`<input type="submit" value="Add New Product" class="btn btn-default" />`

2016-10-24 23:14 UTC, MattKraatz commented on Views/Products/Create.cshtml
> +                <span asp-validation-for="Name" class="text-danger" />
Change all of these self-closing tags to normal tags and validation will work, like so:
`<span asp-validation-for="Name" class="text-danger"></span>`

2016-10-24 23:14 UTC, MattKraatz commented on Controllers/ProductsController.cs
>          public IActionResult Type([FromRoute]int id)
This method doesn't do anything, let's kill it

2016-10-24 23:14 UTC, MattKraatz commented on Controllers/ProductsController.cs
> + *   Task<IActionResult> Create() - retrieve the types and users for the dropdowns
The Create() method also returns a view

2016-10-25 02:06 UTC, Anulfo commented
Although all the span tags were closed, instead of receiving the validation error message, I get the Page Error

2016-10-25 14:48 UTC, MattKraatz approved these changes

2016-10-25 14:48 UTC, MattKraatz commented
LGTM!

2016-10-25 14:57 UTC, daynewright commented
LGTM

2016-10-25 16:46 UTC, merged