87 delete product
TeamCharles/initial-site pull request #95
Opened 2016-10-26 18:53 UTC by garrett-vangilder

## Status
**READY

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

This PR allows for users to delete an item if the user is the associated user to the item.

## Resolves Issue Number

#87 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 87-delete-product
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. View index page
2. Select delete button next to item (red X)
3. You will be rerouted to the product type page associated with the deleted item.

## Impacted Files in Application
List general components of the application that this PR will affect:

* Product Controller and Product Type View

2016-10-26 20:14 UTC, matthamil commented
My `X` isn't red :(

2016-10-26 20:16 UTC, matthamil approved these changes
LGTM

2016-10-26 20:31 UTC, daynewright commented
LGTM

2016-10-27 13:59 UTC, MattKraatz requested changes
Just one small change on my end

2016-10-27 13:59 UTC, MattKraatz commented on Controllers/ProductsController.cs
> +            if (!ModelState.IsValid)
This shouldn't check for ModelState but instead the return of our Linq statement:
`if (originalProduct == null)`

2016-10-27 14:05 UTC, garrett-vangilder commented on Controllers/ProductsController.cs
> +            if (!ModelState.IsValid)
Good call!

2016-10-27 14:05 UTC, Anulfo commented
LGTM

2016-10-27 14:07 UTC, MattKraatz approved these changes

2016-10-27 14:07 UTC, MattKraatz commented
LGTM

2016-10-27 14:27 UTC, merged